version: "3.8"
services:
  # vue-app:
  #   build:
  #     context: ./vue-app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   image: vue-app
  #   volumes:
  #     - ./vue-app:/app
  #   container_name: vue-app

  # nest-api:
  #   build:
  #     context: ./nest-api
  #     dockerfile: Dockerfile
  #   image: nest-api
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   environment:
  #     - .env
  #   volumes:
  #     - ./nest-api:/app
  #   container_name: nest-api

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5433:5432
    volumes:
      - pg-chat_app:/var/lib/postgresql/data
    container_name: chat_app_db
volumes:
  pg-chat_app:
